/**
 * @file SimulationFixedLagSmoother.cpp
 * @brief Fixed-lag smoother for INS/GNSS/PARS simulation data.
 *
 * Reads simulation CSV data (generated by MATLAB) and runs a fixed-lag
 * smoother with CombinedImuFactor, GPSFactor, and PARS (range/azimuth/
 * elevation) factors. Supports both ConstantBias and GaussMarkovBias models.
 */

#include <gtsam/base/Matrix.h>
#include <gtsam/base/Vector.h>
#include <gtsam/geometry/Pose3.h>
#include <gtsam/geometry/Rot3.h>
#include <gtsam/inference/Symbol.h>
#include <gtsam/linear/NoiseModel.h>
#include <gtsam/navigation/CombinedImuFactor.h>
#include <gtsam/navigation/GPSFactor.h>
#include <gtsam/navigation/ImuBias.h>
#include <gtsam/navigation/NavState.h>
#include <gtsam/nonlinear/ISAM2.h>
#include <gtsam/nonlinear/IncrementalFixedLagSmoother.h>
#include <gtsam/nonlinear/NonlinearFactorGraph.h>
#include <gtsam/nonlinear/Values.h>

#include <Eigen/Core>
#include <chrono>
#include <cstdint>
#include <fstream>
#include <iostream>
#include <optional>
#include <sstream>
#include <string>
#include <type_traits>
#include <vector>

#include "PARSAzimuthFactor.hpp"
#include "PARSElevationFactor.hpp"
#include "PARSRangeFactor.hpp"
#include "utils.hpp"

using gtsam::symbol_shorthand::B;
using gtsam::symbol_shorthand::V;
using gtsam::symbol_shorthand::X;

// ============================================================================
// Configuration
// ============================================================================

/// Toggle Gauss-Markov bias model (true) vs constant/random-walk bias (false)
constexpr bool use_gauss_markov = true;

/// Gauss-Markov correlation times [s] (only used when use_gauss_markov = true)
constexpr double tau_acc = 3600.0;
constexpr double tau_gyro = 3600.0;

/// Smoother lag [s]
constexpr double smoother_lag = 10.0;

/// Aiding scheme
enum class Aiding { GNSS, PARSFull };
constexpr Aiding aiding_scheme = Aiding::PARSFull;

/// GNSS bootstrap duration [s] — when using PARS, GNSS is used for the first
/// N seconds to initialise the filter before switching to PARS aiding.
constexpr double gnss_bootstrap_duration = 150.0;

/// Input/output paths
const std::string input_file =
    "/Users/ghms/ws/ntnu/parnav_ins_sim/data/"
    "otter_simulation_data_01_100Hz_noisy_biased_aided_at_10Hz_cpp.csv";
const std::string output_file =
    "/Users/ghms/ws/ntnu/parnav_ins_sim/results/gtsam_fork_test.csv";

// ============================================================================
// Minimal CSV parsing
// ============================================================================

struct SimulationData {
  uint64_t N;
  Eigen::MatrixXd data;

  // Simulation parameters
  auto freq() const -> uint16_t { return static_cast<uint16_t>(data(0, 30)); }
  auto aiding_freq() const -> uint16_t {
    return static_cast<uint16_t>(data(0, 31));
  }
  auto num_locators() const -> uint16_t {
    return static_cast<uint16_t>(data(0, 53));
  }
  auto time() const -> Eigen::VectorXd { return data.col(23); }

  // True state
  auto true_pos() const -> Eigen::MatrixXd {
    return data.block(0, 1, N, 3).transpose();
  }
  auto true_vel() const -> Eigen::MatrixXd {
    return data.block(0, 4, N, 3).transpose();
  }
  auto true_att() const -> Eigen::MatrixXd {
    return data.block(0, 7, N, 4).transpose();
  }
  auto true_acc_bias() const -> Eigen::MatrixXd {
    return data.block(0, 17, N, 3).transpose();
  }
  auto true_gyro_bias() const -> Eigen::MatrixXd {
    return data.block(0, 20, N, 3).transpose();
  }

  // IMU measurements (specific force and angular rate)
  auto imu_f() const -> Eigen::MatrixXd { return data.block(0, 11, N, 3); }
  auto imu_w() const -> Eigen::MatrixXd { return data.block(0, 14, N, 3); }

  // GNSS measurements
  auto gnss_pos() const -> Eigen::MatrixXd {
    return data.block(0, 24, N, 3).transpose();
  }

  // Initial state estimates
  auto init_pos() const -> Eigen::Vector3d {
    return data.block(0, 33, 1, 3).transpose();
  }
  auto init_vel() const -> Eigen::Vector3d {
    return data.block(0, 37, 1, 3).transpose();
  }
  auto init_att() const -> Eigen::Vector4d {
    return data.block(0, 41, 1, 4).transpose();
  }
  auto init_acc_bias() const -> Eigen::Vector3d {
    return data.block(0, 46, 1, 3).transpose();
  }
  auto init_gyro_bias() const -> Eigen::Vector3d {
    return data.block(0, 50, 1, 3).transpose();
  }

  // Initial state uncertainties (1-sigma)
  auto A_pos() const -> double { return data(0, 32); }
  auto A_vel() const -> double { return data(0, 36); }
  auto A_att() const -> double { return data(0, 40); }
  auto A_acc_bias() const -> double { return data(0, 45); }
  auto A_gyro_bias() const -> double { return data(0, 49); }

  // PARS beacon measurements: z = [range, elevation, azimuth] per locator
  struct PARSBeacon {
    size_t id;
    Eigen::MatrixXd z;       // 3 x N (range, elevation, azimuth)
    Eigen::Vector3d origin;  // locator position in NED
  };

  auto pars_beacons() const -> std::vector<PARSBeacon> {
    uint16_t n_loc = num_locators();
    std::vector<PARSBeacon> beacons;
    for (uint16_t i = 0; i < n_loc; ++i) {
      size_t z_start = 54 + 3 * i;
      size_t origin_start = 54 + n_loc * 3 + 3 * i;
      Eigen::MatrixXd z = data.block(0, z_start, N, 3).transpose();
      Eigen::Vector3d origin = data.block(0, origin_start, 1, 3).transpose();
      beacons.push_back({i, z, origin});
    }
    return beacons;
  }
};

auto read_simulation_csv(const std::string& filename)
    -> std::optional<SimulationData> {
  std::ifstream file(filename);
  if (!file) {
    std::cerr << "Error: Could not open file " << filename << "\n";
    return std::nullopt;
  }

  std::string line;
  std::vector<double> values;
  int rows = 0;
  while (std::getline(file, line)) {
    std::stringstream ss(line);
    std::string cell;
    while (std::getline(ss, cell, ',')) {
      values.push_back(std::stod(cell));
    }
    ++rows;
  }

  SimulationData sd;
  sd.N = rows;
  sd.data = Eigen::Map<const Eigen::Matrix<double, Eigen::Dynamic,
                                           Eigen::Dynamic, Eigen::RowMajor>>(
      values.data(), rows, values.size() / rows);
  return sd;
}

// ============================================================================
// Main estimation loop — templated on bias type
// ============================================================================

template <class BIAS>
void run_estimation(const SimulationData& sd) {
  using Preintegration = gtsam::ManifoldPreintegration<BIAS>;
  using PIM = gtsam::PreintegratedCombinedMeasurementsT<Preintegration, BIAS>;
  using Factor = gtsam::CombinedImuFactorT<PIM, BIAS>;

  const double g0 = 9.81;
  const double dt = 1.0 / sd.freq();

  // --- Sensor noise parameters ---
  double vrw = 0.07;
  double arw = 0.15;
  double bias_instability_acc = 0.05;  // milli g
  double bias_instability_ars = 0.5;   // deg per hour
  double T_acc = 3600.0;
  double T_ars = 3600.0;

  double sigma_v = vrw / 60.0;
  double sigma_q = (arw / 60.0) * deg2rad(1.0);
  double sigma_b_acc =
      std::sqrt((2.0 / T_acc) * (bias_instability_acc * (g0 / 1000.0)));
  double sigma_b_ars =
      std::sqrt((2.0 / T_ars) * (bias_instability_ars / 3600.0) * deg2rad(1.0));

  // Preintegration params
  auto p = gtsam::PreintegrationCombinedParamsT<BIAS>::MakeSharedD(g0);
  p->accelerometerCovariance = gtsam::I_3x3 * sigma_v * sigma_v;
  p->gyroscopeCovariance = gtsam::I_3x3 * sigma_q * sigma_q;
  p->integrationCovariance = gtsam::I_3x3 * 1e-10;
  p->biasAccCovariance = gtsam::I_3x3 * sigma_b_acc * sigma_b_acc;
  p->biasOmegaCovariance = gtsam::I_3x3 * sigma_b_ars * sigma_b_ars;

  // --- Initial state ---
  Eigen::Vector4d q0 = sd.init_att();  // qx, qy, qz, qw
  gtsam::Rot3 R0 = gtsam::Rot3::Quaternion(q0(0), q0(1), q0(2), q0(3));
  gtsam::Point3 p0 = sd.init_pos();
  gtsam::Pose3 pose0(R0, p0);
  gtsam::Vector3 v0 = sd.init_vel();

  BIAS prior_bias;
  if constexpr (std::is_same_v<BIAS, gtsam::imuBias::GaussMarkovBias>) {
    prior_bias = gtsam::imuBias::GaussMarkovBias(
        gtsam::Vector3::Zero(), gtsam::Vector3::Zero(), tau_acc, tau_gyro);
  }

  // --- Prior noise models ---
  auto pose_noise = gtsam::noiseModel::Diagonal::Sigmas(
      (gtsam::Vector(6) << sd.A_att(), sd.A_att(), sd.A_att(), sd.A_pos(),
       sd.A_pos(), sd.A_pos())
          .finished());
  auto vel_noise = gtsam::noiseModel::Isotropic::Sigma(3, sd.A_vel());
  auto bias_noise = gtsam::noiseModel::Diagonal::Sigmas(
      (gtsam::Vector(6) << sd.A_acc_bias(), sd.A_acc_bias(), sd.A_acc_bias(),
       sd.A_gyro_bias(), sd.A_gyro_bias(), sd.A_gyro_bias())
          .finished());

  // GNSS noise model
  auto gnss_noise = gtsam::noiseModel::Diagonal::Sigmas(
      (gtsam::Vector(3) << 1.5, 1.5, 3.0).finished());

  // PARS noise models
  double sigma_range = 5;
  double sigma_azimuth = 7.0 * deg2rad(1.0);
  double sigma_elevation = 7.0 * deg2rad(1.0);
  auto range_noise = gtsam::noiseModel::Isotropic::Sigma(1, sigma_range);
  auto azimuth_noise = gtsam::noiseModel::Isotropic::Sigma(1, sigma_azimuth);
  auto elevation_noise =
      gtsam::noiseModel::Isotropic::Sigma(1, sigma_elevation);

  // --- Fixed-lag smoother setup ---
  gtsam::ISAM2Params isam_params;
  isam_params.relinearizeSkip = 1;
  isam_params.relinearizeThreshold = 0.01;
  isam_params.findUnusedFactorSlots = true;
  gtsam::IncrementalFixedLagSmoother smoother(smoother_lag, isam_params);

  // Insert priors
  gtsam::NonlinearFactorGraph graph;
  gtsam::Values values;
  gtsam::FixedLagSmoother::KeyTimestampMap timestamps;

  graph.addPrior<gtsam::Pose3>(X(0), pose0, pose_noise);
  graph.addPrior<gtsam::Vector3>(V(0), v0, vel_noise);
  graph.addPrior<BIAS>(B(0), prior_bias, bias_noise);
  values.insert(X(0), pose0);
  values.insert(V(0), v0);
  values.insert(B(0), prior_bias);
  timestamps[X(0)] = 0.0;
  timestamps[V(0)] = 0.0;
  timestamps[B(0)] = 0.0;

  smoother.update(graph, values, timestamps);

  // --- Preintegrator ---
  auto preintegrated = std::make_shared<PIM>(p, prior_bias);

  gtsam::NavState prev_state(pose0, v0);
  BIAS prev_bias_estimate = prior_bias;

  // PARS beacons
  auto beacons = sd.pars_beacons();

  // IMU data
  Eigen::MatrixXd imu_f = sd.imu_f();
  Eigen::MatrixXd imu_w = sd.imu_w();
  Eigen::MatrixXd gnss_pos = sd.gnss_pos();
  Eigen::MatrixXd true_pos = sd.true_pos();
  Eigen::MatrixXd true_vel = sd.true_vel();
  Eigen::MatrixXd true_att = sd.true_att();       // 4 x N (qx, qy, qz, qw)
  Eigen::MatrixXd true_ab = sd.true_acc_bias();   // 3 x N
  Eigen::MatrixXd true_gb = sd.true_gyro_bias();  // 3 x N

  // Result storage
  std::vector<Eigen::Vector3d> est_pos, est_vel, pos_err, vel_err;
  std::vector<Eigen::Vector3d> att_err, acc_bias_err, gyro_bias_err;
  std::vector<gtsam::Rot3> est_att;
  std::vector<Eigen::Vector3d> est_acc_bias, est_gyro_bias;
  // 3-sigma bounds (15 states: att_rpy(3), pos_ned(3), vel_ned(3), ab(3),
  // gb(3))
  std::vector<Eigen::Matrix<double, 15, 1>> three_sigma;
  est_pos.push_back(p0);
  est_vel.push_back(v0);
  est_att.push_back(R0);

  int correction_count = 0;

  const auto start_time = std::chrono::system_clock::now();

  for (uint64_t idx = 1; idx < sd.N; ++idx) {
    Eigen::Vector3d f = imu_f.row(idx).transpose();
    Eigen::Vector3d w = imu_w.row(idx).transpose();
    preintegrated->integrateMeasurement(f, w, dt);

    bool is_update_step = (idx + 1) % 10 == 0;

    if (is_update_step) {
      correction_count++;
      double timestamp = idx * dt;

      graph.resize(0);
      values.clear();
      timestamps.clear();

      // Add CombinedImuFactor
      Factor imu_factor(X(correction_count - 1), V(correction_count - 1),
                        X(correction_count), V(correction_count),
                        B(correction_count - 1), B(correction_count),
                        *preintegrated);
      graph.add(imu_factor);

      // Predict state for initial values
      gtsam::NavState prop_state =
          preintegrated->predict(prev_state, prev_bias_estimate);

      values.insert(X(correction_count), prop_state.pose());
      values.insert(V(correction_count), prop_state.v());
      values.insert(B(correction_count), prev_bias_estimate);

      timestamps[X(correction_count)] = timestamp;
      timestamps[V(correction_count)] = timestamp;
      timestamps[B(correction_count)] = timestamp;

      // Determine active aiding: when using PARS, bootstrap with GNSS first
      bool in_bootstrap = (timestamp < gnss_bootstrap_duration);
      Aiding active_aiding = (aiding_scheme == Aiding::PARSFull && in_bootstrap)
                                 ? Aiding::GNSS
                                 : aiding_scheme;

      // Add aiding factors
      if (active_aiding == Aiding::GNSS) {
        gtsam::Point3 gps_meas(gnss_pos(0, idx), gnss_pos(1, idx),
                               gnss_pos(2, idx));
        gtsam::GPSFactor gps_factor(X(correction_count), gps_meas, gnss_noise);
        graph.add(gps_factor);
      } else if (active_aiding == Aiding::PARSFull) {
        for (const auto& beacon : beacons) {
          double range = beacon.z(0, idx);
          double elevation = beacon.z(1, idx);
          double azimuth = beacon.z(2, idx);

          graph.add(PARS::RangeFactor<gtsam::Pose3>(
              X(correction_count), range_noise, range, beacon.origin));
          graph.add(PARS::AzimuthFactor<gtsam::Pose3>(
              X(correction_count), azimuth_noise, azimuth, beacon.origin));
          graph.add(PARS::ElevationFactor<gtsam::Pose3>(
              X(correction_count), elevation_noise, elevation, beacon.origin));
        }
      }

      // Update smoother
      smoother.update(graph, values, timestamps);

      // Extract results
      gtsam::Values result = smoother.calculateEstimate();
      prev_state =
          gtsam::NavState(result.at<gtsam::Pose3>(X(correction_count)),
                          result.at<gtsam::Vector3>(V(correction_count)));
      prev_bias_estimate = result.at<BIAS>(B(correction_count));

      preintegrated->resetIntegrationAndSetBias(prev_bias_estimate);

      // Store estimates
      est_pos.push_back(prev_state.pose().translation());
      est_vel.push_back(prev_state.v());
      est_att.push_back(prev_state.pose().rotation());
      est_acc_bias.push_back(prev_bias_estimate.accelerometer());
      est_gyro_bias.push_back(prev_bias_estimate.gyroscope());

      // Compute errors
      Eigen::Vector3d p_err =
          prev_state.pose().translation() -
          Eigen::Vector3d(true_pos(0, idx), true_pos(1, idx), true_pos(2, idx));
      Eigen::Vector3d v_err =
          prev_state.v() -
          Eigen::Vector3d(true_vel(0, idx), true_vel(1, idx), true_vel(2, idx));

      // Attitude error (Euler angles): R_err = R_true^T * R_est
      gtsam::Rot3 R_true =
          gtsam::Rot3::Quaternion(true_att(0, idx), true_att(1, idx),
                                  true_att(2, idx), true_att(3, idx));
      Eigen::Vector3d a_err(
          ssa(prev_state.pose().rotation().roll() - R_true.roll()),
          ssa(prev_state.pose().rotation().pitch() - R_true.pitch()),
          ssa(prev_state.pose().rotation().yaw() - R_true.yaw()));

      // Bias errors
      Eigen::Vector3d ab_err =
          prev_bias_estimate.accelerometer() -
          Eigen::Vector3d(true_ab(0, idx), true_ab(1, idx), true_ab(2, idx));
      Eigen::Vector3d gb_err =
          prev_bias_estimate.gyroscope() -
          Eigen::Vector3d(true_gb(0, idx), true_gb(1, idx), true_gb(2, idx));

      pos_err.push_back(p_err);
      vel_err.push_back(v_err);
      att_err.push_back(a_err);
      acc_bias_err.push_back(ab_err);
      gyro_bias_err.push_back(gb_err);

      // Extract 3-sigma bounds from marginal covariances
      // Pose3 cov is 6x6: [rot(3), pos(3)]; Vel is 3x3; Bias is 6x6: [acc(3),
      // gyro(3)]
      Eigen::Matrix<double, 15, 1> sig3;
      try {
        gtsam::Matrix pose_cov =
            smoother.marginalCovariance(X(correction_count));
        gtsam::Matrix vel_cov =
            smoother.marginalCovariance(V(correction_count));
        gtsam::Matrix bias_cov =
            smoother.marginalCovariance(B(correction_count));
        // roll, pitch, yaw (rotation block, indices 0-2)
        sig3(0) = 3.0 * std::sqrt(pose_cov(0, 0));
        sig3(1) = 3.0 * std::sqrt(pose_cov(1, 1));
        sig3(2) = 3.0 * std::sqrt(pose_cov(2, 2));
        // N, E, D position (translation block, indices 3-5)
        sig3(3) = 3.0 * std::sqrt(pose_cov(3, 3));
        sig3(4) = 3.0 * std::sqrt(pose_cov(4, 4));
        sig3(5) = 3.0 * std::sqrt(pose_cov(5, 5));
        // N, E, D velocity
        sig3(6) = 3.0 * std::sqrt(vel_cov(0, 0));
        sig3(7) = 3.0 * std::sqrt(vel_cov(1, 1));
        sig3(8) = 3.0 * std::sqrt(vel_cov(2, 2));
        // acc bias x, y, z
        sig3(9) = 3.0 * std::sqrt(bias_cov(0, 0));
        sig3(10) = 3.0 * std::sqrt(bias_cov(1, 1));
        sig3(11) = 3.0 * std::sqrt(bias_cov(2, 2));
        // gyro bias x, y, z
        sig3(12) = 3.0 * std::sqrt(bias_cov(3, 3));
        sig3(13) = 3.0 * std::sqrt(bias_cov(4, 4));
        sig3(14) = 3.0 * std::sqrt(bias_cov(5, 5));
      } catch (const std::exception& e) {
        sig3.setZero();
      }
      three_sigma.push_back(sig3);

      if (correction_count % 100 == 0) {
        printf("Step %llu/%llu | Pos: %.4f m | Vel: %.4f m/s | Att: %.4f deg\n",
               static_cast<unsigned long long>(idx),
               static_cast<unsigned long long>(sd.N), p_err.norm(),
               v_err.norm(), rad2deg(a_err.norm()));
      }
    }
  }

  auto end_time = std::chrono::system_clock::now();
  std::chrono::duration<double> elapsed = end_time - start_time;
  printf("Elapsed time: %.3f s | Data horizon: %.1f s\n", elapsed.count(),
         sd.N * dt);

  // --- Export results to CSV ---
  std::ofstream out(output_file);
  if (!out) {
    std::cerr << "Error: Could not open output file " << output_file << "\n";
    return;
  }

  out << "pos_n,pos_e,pos_d,vel_n,vel_e,vel_d,roll,pitch,yaw,"
      << "pos_err_n,pos_err_e,pos_err_d,vel_err_n,vel_err_e,vel_err_d,"
      << "att_err_roll,att_err_pitch,att_err_yaw,"
      << "acc_bias_err_x,acc_bias_err_y,acc_bias_err_z,"
      << "gyro_bias_err_x,gyro_bias_err_y,gyro_bias_err_z,"
      << "sig3_roll,sig3_pitch,sig3_yaw,"
      << "sig3_pos_n,sig3_pos_e,sig3_pos_d,"
      << "sig3_vel_n,sig3_vel_e,sig3_vel_d,"
      << "sig3_ab_x,sig3_ab_y,sig3_ab_z,"
      << "sig3_gb_x,sig3_gb_y,sig3_gb_z\n";

  size_t n_results = std::min(est_pos.size(), pos_err.size());
  for (size_t i = 0; i < n_results; ++i) {
    const auto& ep = est_pos[i + 1];  // skip initial
    const auto& ev = est_vel[i + 1];
    const auto& ea = est_att[i + 1];
    const auto& pe = pos_err[i];
    const auto& ve = vel_err[i];
    const auto& ae = att_err[i];
    const auto& abe = acc_bias_err[i];
    const auto& gbe = gyro_bias_err[i];
    const auto& s3 = three_sigma[i];
    char buf[2048];
    snprintf(buf, sizeof(buf),
             "%.6f,%.6f,%.6f,%.6f,%.6f,%.6f,%.6f,%.6f,%.6f,"
             "%.6f,%.6f,%.6f,%.6f,%.6f,%.6f,"
             "%.6f,%.6f,%.6f,"
             "%.6f,%.6f,%.6f,"
             "%.6f,%.6f,%.6f,"
             "%.8f,%.8f,%.8f,"
             "%.8f,%.8f,%.8f,"
             "%.8f,%.8f,%.8f,"
             "%.8f,%.8f,%.8f,"
             "%.8f,%.8f,%.8f\n",
             ep.x(), ep.y(), ep.z(), ev.x(), ev.y(), ev.z(), ea.roll(),
             ea.pitch(), ea.yaw(), pe.x(), pe.y(), pe.z(), ve.x(), ve.y(),
             ve.z(), ae.x(), ae.y(), ae.z(), abe.x(), abe.y(), abe.z(), gbe.x(),
             gbe.y(), gbe.z(), s3(0), s3(1), s3(2), s3(3), s3(4), s3(5), s3(6),
             s3(7), s3(8), s3(9), s3(10), s3(11), s3(12), s3(13), s3(14));
    out << buf;
  }

  printf("Saved results to %s\n", output_file.c_str());

#ifdef GTSAM_TANGENT_PREINTEGRATION
  printf("Preintegration: Tangent\n");
#else
  printf("Preintegration: Manifold\n");
#endif
}

// ============================================================================
// Main
// ============================================================================

int main(int /*argc*/, char* /*argv*/[]) {
  printf("Reading simulation data from: %s\n", input_file.c_str());
  auto sd = read_simulation_csv(input_file);
  if (!sd) {
    return 1;
  }
  printf("Loaded %llu time steps at %d Hz\n",
         static_cast<unsigned long long>(sd->N), sd->freq());
  printf("Number of PARS beacons: %d\n", sd->num_locators());

  try {
    if constexpr (use_gauss_markov) {
      printf(
          "Using 1st-order Gauss-Markov bias model (tau_acc=%.0f s, "
          "tau_gyro=%.0f s)\n",
          tau_acc, tau_gyro);
      run_estimation<gtsam::imuBias::GaussMarkovBias>(*sd);
    } else {
      printf("Using constant (random walk) bias model\n");
      run_estimation<gtsam::imuBias::ConstantBias>(*sd);
    }
  } catch (const gtsam::IndeterminantLinearSystemException& e) {
    std::cerr << "IndeterminantLinearSystemException: " << e.what() << "\n";
  } catch (const std::exception& e) {
    std::cerr << "Exception: " << e.what() << "\n";
  }

  return 0;
}
