/**
 * @file SimulationFixedLagSmoother.cpp
 * @brief Fixed-lag smoother for INS/GNSS/PARS simulation data.
 *
 * Reads simulation CSV data (generated by MATLAB) and runs a fixed-lag
 * smoother with CombinedImuFactor, GPSFactor, and PARS (range/azimuth/
 * elevation) factors. Templated on:
 *   - BIAS:      imuBias::ConstantBias | imuBias::GaussMarkovBias
 *   - UseSE23:   false -> legacy NavState-based CombinedImuFactor on
 *                         (Pose3, Vector3, BIAS)
 *                true  -> SE_2(3) CombinedImuFactor2 on (ExtendedPose3, BIAS)
 *
 * Output CSVs get an `_se23` suffix when UseSE23 is true.
 */

#include <gtsam/base/Matrix.h>
#include <gtsam/base/Vector.h>
#include <gtsam/geometry/ExtendedPose3.h>
#include <gtsam/geometry/Pose3.h>
#include <gtsam/geometry/Rot3.h>
#include <gtsam/inference/Symbol.h>
#include <gtsam/linear/NoiseModel.h>
#include <gtsam/navigation/CombinedImuFactor.h>
#include <gtsam/navigation/CombinedImuFactor2.h>
#include <gtsam/navigation/GPSFactor.h>
#include <gtsam/navigation/ImuBias.h>
#include <gtsam/navigation/ManifoldPreintegrationSE23.h>
#include <gtsam/navigation/NavState.h>
#include <gtsam/nonlinear/ISAM2.h>
#include <gtsam/nonlinear/IncrementalFixedLagSmoother.h>
#include <gtsam/nonlinear/NonlinearFactor.h>
#include <gtsam/nonlinear/NonlinearFactorGraph.h>
#include <gtsam/nonlinear/Values.h>

#include <Eigen/Core>
#include <chrono>
#include <cstdint>
#include <fstream>
#include <iostream>
#include <optional>
#include <sstream>
#include <string>
#include <type_traits>
#include <vector>

#include "AzimuthFactor.hpp"
#include "ElevationFactor.hpp"
#include "RangeFactor.hpp"
#include "utils.hpp"

using parnav::deg2rad;
using parnav::rad2deg;
using parnav::ssa;

using gtsam::symbol_shorthand::B;
using gtsam::symbol_shorthand::V;
using gtsam::symbol_shorthand::X;

// ============================================================================
// Configuration
// ============================================================================

/// Gauss-Markov correlation times [s] (only used when --gm is selected)
constexpr double tau_acc = 3600.0;
constexpr double tau_gyro = 3600.0;

/// Smoother lag [s]
constexpr double smoother_lag = 10.0;

/// Aiding scheme
enum class Aiding { GNSS, PARSFull };

/// GNSS bootstrap duration [s] — when using PARS, GNSS is used for the first
/// N seconds to initialise the filter before switching to PARS aiding.
constexpr double gnss_bootstrap_duration = 150.0;

/// Default input/output paths (overridable via --input / --output-dir)
const std::string default_input_file =
    "/Users/ghms/ws/ntnu/parnav_ins_sim/data/"
    "otter_simulation_data_01_100Hz_noisy_biased_aided_at_10Hz_cpp.csv";
const std::string default_output_dir =
    "/Users/ghms/ws/ntnu/parnav_ins_sim/results/";

/// Runtime options populated from CLI.
struct Options {
  bool use_gauss_markov = true;
  bool use_se23 = true;
  Aiding aiding_scheme = Aiding::PARSFull;
  std::string input_file = default_input_file;
  std::string output_dir = default_output_dir;
};

// ============================================================================
// Minimal CSV parsing
// ============================================================================

struct SimulationData {
  uint64_t N;
  Eigen::MatrixXd data;

  // Simulation parameters
  auto freq() const -> uint16_t { return static_cast<uint16_t>(data(0, 30)); }
  auto aiding_freq() const -> uint16_t {
    return static_cast<uint16_t>(data(0, 31));
  }
  auto num_locators() const -> uint16_t {
    return static_cast<uint16_t>(data(0, 53));
  }
  auto time() const -> Eigen::VectorXd { return data.col(23); }

  // True state
  auto true_pos() const -> Eigen::MatrixXd {
    return data.block(0, 1, N, 3).transpose();
  }
  auto true_vel() const -> Eigen::MatrixXd {
    return data.block(0, 4, N, 3).transpose();
  }
  auto true_att() const -> Eigen::MatrixXd {
    return data.block(0, 7, N, 4).transpose();
  }
  auto true_acc_bias() const -> Eigen::MatrixXd {
    return data.block(0, 17, N, 3).transpose();
  }
  auto true_gyro_bias() const -> Eigen::MatrixXd {
    return data.block(0, 20, N, 3).transpose();
  }

  // IMU measurements (specific force and angular rate)
  auto imu_f() const -> Eigen::MatrixXd { return data.block(0, 11, N, 3); }
  auto imu_w() const -> Eigen::MatrixXd { return data.block(0, 14, N, 3); }

  // GNSS measurements
  auto gnss_pos() const -> Eigen::MatrixXd {
    return data.block(0, 24, N, 3).transpose();
  }

  // Initial state estimates
  auto init_pos() const -> Eigen::Vector3d {
    return data.block(0, 33, 1, 3).transpose();
  }
  auto init_vel() const -> Eigen::Vector3d {
    return data.block(0, 37, 1, 3).transpose();
  }
  auto init_att() const -> Eigen::Vector4d {
    return data.block(0, 41, 1, 4).transpose();
  }
  auto init_acc_bias() const -> Eigen::Vector3d {
    return data.block(0, 46, 1, 3).transpose();
  }
  auto init_gyro_bias() const -> Eigen::Vector3d {
    return data.block(0, 50, 1, 3).transpose();
  }

  // Initial state uncertainties (1-sigma)
  auto A_pos() const -> double { return data(0, 32); }
  auto A_vel() const -> double { return data(0, 36); }
  auto A_att() const -> double { return data(0, 40); }
  auto A_acc_bias() const -> double { return data(0, 45); }
  auto A_gyro_bias() const -> double { return data(0, 49); }

  // PARS beacon measurements: z = [range, elevation, azimuth] per locator
  struct PARSBeacon {
    size_t id;
    Eigen::MatrixXd z;       // 3 x N (range, elevation, azimuth)
    Eigen::Vector3d origin;  // locator position in NED
  };

  auto pars_beacons() const -> std::vector<PARSBeacon> {
    uint16_t n_loc = num_locators();
    std::vector<PARSBeacon> beacons;
    for (uint16_t i = 0; i < n_loc; ++i) {
      size_t z_start = 54 + 3 * i;
      size_t origin_start = 54 + n_loc * 3 + 3 * i;
      Eigen::MatrixXd z = data.block(0, z_start, N, 3).transpose();
      Eigen::Vector3d origin = data.block(0, origin_start, 1, 3).transpose();
      beacons.push_back({i, z, origin});
    }
    return beacons;
  }
};

auto read_simulation_csv(const std::string& filename)
    -> std::optional<SimulationData> {
  std::ifstream file(filename);
  if (!file) {
    std::cerr << "Error: Could not open file " << filename << "\n";
    return std::nullopt;
  }

  std::string line;
  std::vector<double> values;
  int rows = 0;
  while (std::getline(file, line)) {
    std::stringstream ss(line);
    std::string cell;
    while (std::getline(ss, cell, ',')) {
      values.push_back(std::stod(cell));
    }
    ++rows;
  }

  SimulationData sd;
  sd.N = rows;
  sd.data = Eigen::Map<const Eigen::Matrix<double, Eigen::Dynamic,
                                           Eigen::Dynamic, Eigen::RowMajor>>(
      values.data(), rows, values.size() / rows);
  return sd;
}

// ============================================================================
// GPS factor on ExtendedPose3
// ============================================================================

/// Minimal position-only measurement factor on ExtendedPose3.
/// Residual = position(X) - measured, so the 3x9 Jacobian picks the rho block.
class GPSFactorSE23
    : public gtsam::NoiseModelFactorN<gtsam::ExtendedPose3> {
  gtsam::Point3 measured_;

 public:
  GPSFactorSE23(gtsam::Key key, const gtsam::Point3& measured,
                const gtsam::SharedNoiseModel& model)
      : gtsam::NoiseModelFactorN<gtsam::ExtendedPose3>(model, key),
        measured_(measured) {}

  gtsam::Vector evaluateError(
      const gtsam::ExtendedPose3& X,
      gtsam::OptionalMatrixType H) const override {
    if (H) {
      gtsam::Matrix H_p(3, 9);
      gtsam::Point3 p = X.position(H_p);
      *H = H_p;
      return p - measured_;
    }
    return X.position() - measured_;
  }
};

// ============================================================================
// Main estimation loop — templated on bias + preintegrator family
// ============================================================================

template <class BIAS, bool UseSE23>
void run_estimation(const SimulationData& sd, const Options& opts) {
  // -- Select preintegrator / factor family --
  using PIMLegacy =
      gtsam::PreintegratedCombinedMeasurementsT<
          gtsam::ManifoldPreintegration<BIAS>, BIAS>;
  using FactorLegacy = gtsam::CombinedImuFactorT<PIMLegacy, BIAS>;

  using PIMSE23 =
      gtsam::PreintegratedCombinedMeasurements2T<
          gtsam::ManifoldPreintegrationSE23<BIAS>, BIAS>;
  using FactorSE23 = gtsam::CombinedImuFactor2T<PIMSE23, BIAS>;

  using PIM = std::conditional_t<UseSE23, PIMSE23, PIMLegacy>;
  using Factor = std::conditional_t<UseSE23, FactorSE23, FactorLegacy>;
  using StateType = std::conditional_t<UseSE23, gtsam::ExtendedPose3,
                                       gtsam::NavState>;

  const double g0 = 9.81;
  const double dt = 1.0 / sd.freq();

  // --- Sensor noise parameters ---
  double vrw = 0.07;
  double arw = 0.15;
  double bias_instability_acc = 0.05;  // milli g
  double bias_instability_ars = 0.5;   // deg per hour
  double T_acc = 3600.0;
  double T_ars = 3600.0;

  double sigma_v = vrw / 60.0;
  double sigma_q = (arw / 60.0) * deg2rad(1.0);
  double sigma_b_acc =
      std::sqrt((2.0 / T_acc) * (bias_instability_acc * (g0 / 1000.0)));
  double sigma_b_ars =
      std::sqrt((2.0 / T_ars) * (bias_instability_ars / 3600.0) * deg2rad(1.0));

  // Preintegration params
  auto p = gtsam::PreintegrationCombinedParamsT<BIAS>::MakeSharedD(g0);
  p->accelerometerCovariance = gtsam::I_3x3 * sigma_v * sigma_v;
  p->gyroscopeCovariance = gtsam::I_3x3 * sigma_q * sigma_q;
  p->integrationCovariance = gtsam::I_3x3 * 1e-10;
  p->biasAccCovariance = gtsam::I_3x3 * sigma_b_acc * sigma_b_acc;
  p->biasOmegaCovariance = gtsam::I_3x3 * sigma_b_ars * sigma_b_ars;

  // --- Initial state ---
  Eigen::Vector4d q0 = sd.init_att();  // qx, qy, qz, qw
  gtsam::Rot3 R0 = gtsam::Rot3::Quaternion(q0(0), q0(1), q0(2), q0(3));
  gtsam::Point3 p0 = sd.init_pos();
  gtsam::Pose3 pose0(R0, p0);
  gtsam::Vector3 v0 = sd.init_vel();

  BIAS prior_bias;
  if constexpr (std::is_same_v<BIAS, gtsam::imuBias::GaussMarkovBias>) {
    prior_bias = gtsam::imuBias::GaussMarkovBias(
        gtsam::Vector3::Zero(), gtsam::Vector3::Zero(), tau_acc, tau_gyro);
  }

  // --- Prior noise models ---
  auto bias_noise = gtsam::noiseModel::Diagonal::Sigmas(
      (gtsam::Vector(6) << sd.A_acc_bias(), sd.A_acc_bias(), sd.A_acc_bias(),
       sd.A_gyro_bias(), sd.A_gyro_bias(), sd.A_gyro_bias())
          .finished());

  // GNSS noise model
  auto gnss_noise = gtsam::noiseModel::Diagonal::Sigmas(
      (gtsam::Vector(3) << 1.5, 1.5, 3.0).finished());

  // PARS noise models
  double sigma_range = 5;
  double sigma_azimuth = 7.0 * deg2rad(1.0);
  double sigma_elevation = 7.0 * deg2rad(1.0);
  auto range_noise = gtsam::noiseModel::Isotropic::Sigma(1, sigma_range);
  auto azimuth_noise = gtsam::noiseModel::Isotropic::Sigma(1, sigma_azimuth);
  auto elevation_noise =
      gtsam::noiseModel::Isotropic::Sigma(1, sigma_elevation);

  // --- Fixed-lag smoother setup ---
  gtsam::ISAM2Params isam_params;
  isam_params.relinearizeSkip = 1;
  isam_params.relinearizeThreshold = 0.01;
  isam_params.findUnusedFactorSlots = true;
  gtsam::IncrementalFixedLagSmoother smoother(smoother_lag, isam_params);

  // Insert priors
  gtsam::NonlinearFactorGraph graph;
  gtsam::Values values;
  gtsam::FixedLagSmoother::KeyTimestampMap timestamps;

  if constexpr (UseSE23) {
    // 9-dim ExtendedPose3 prior: order = (theta, nu, rho)
    auto epose_noise = gtsam::noiseModel::Diagonal::Sigmas(
        (gtsam::Vector(9) << sd.A_att(), sd.A_att(), sd.A_att(), sd.A_vel(),
         sd.A_vel(), sd.A_vel(), sd.A_pos(), sd.A_pos(), sd.A_pos())
            .finished());
    gtsam::ExtendedPose3 ext0(R0, v0, p0);
    graph.addPrior<gtsam::ExtendedPose3>(X(0), ext0, epose_noise);
    graph.addPrior<BIAS>(B(0), prior_bias, bias_noise);
    values.insert(X(0), ext0);
    values.insert(B(0), prior_bias);
    timestamps[X(0)] = 0.0;
    timestamps[B(0)] = 0.0;
  } else {
    auto pose_noise = gtsam::noiseModel::Diagonal::Sigmas(
        (gtsam::Vector(6) << sd.A_att(), sd.A_att(), sd.A_att(), sd.A_pos(),
         sd.A_pos(), sd.A_pos())
            .finished());
    auto vel_noise = gtsam::noiseModel::Isotropic::Sigma(3, sd.A_vel());
    graph.addPrior<gtsam::Pose3>(X(0), pose0, pose_noise);
    graph.addPrior<gtsam::Vector3>(V(0), v0, vel_noise);
    graph.addPrior<BIAS>(B(0), prior_bias, bias_noise);
    values.insert(X(0), pose0);
    values.insert(V(0), v0);
    values.insert(B(0), prior_bias);
    timestamps[X(0)] = 0.0;
    timestamps[V(0)] = 0.0;
    timestamps[B(0)] = 0.0;
  }

  smoother.update(graph, values, timestamps);

  // --- Preintegrator ---
  auto preintegrated = std::make_shared<PIM>(p, prior_bias);

  // Previous state (rolled forward). For SE23 it's an ExtendedPose3; for
  // legacy we keep a NavState composed of (pose, vel).
  StateType prev_state = [&] {
    if constexpr (UseSE23) {
      return gtsam::ExtendedPose3(R0, v0, p0);
    } else {
      return gtsam::NavState(pose0, v0);
    }
  }();
  BIAS prev_bias_estimate = prior_bias;

  // PARS beacons
  auto beacons = sd.pars_beacons();

  // IMU data
  Eigen::MatrixXd imu_f = sd.imu_f();
  Eigen::MatrixXd imu_w = sd.imu_w();
  Eigen::MatrixXd gnss_pos = sd.gnss_pos();
  Eigen::MatrixXd true_pos = sd.true_pos();
  Eigen::MatrixXd true_vel = sd.true_vel();
  Eigen::MatrixXd true_att = sd.true_att();       // 4 x N (qx, qy, qz, qw)
  Eigen::MatrixXd true_ab = sd.true_acc_bias();   // 3 x N
  Eigen::MatrixXd true_gb = sd.true_gyro_bias();  // 3 x N

  // Result storage
  std::vector<Eigen::Vector3d> est_pos, est_vel, pos_err, vel_err;
  std::vector<Eigen::Vector3d> att_err, acc_bias_err, gyro_bias_err;
  std::vector<gtsam::Rot3> est_att;
  std::vector<Eigen::Vector3d> est_acc_bias, est_gyro_bias;
  // 3-sigma bounds (15 states: att_rpy(3), pos_ned(3), vel_ned(3), ab(3),
  // gb(3))
  std::vector<Eigen::Matrix<double, 15, 1>> three_sigma;
  est_pos.push_back(p0);
  est_vel.push_back(v0);
  est_att.push_back(R0);

  int correction_count = 0;

  const auto start_time = std::chrono::system_clock::now();

  for (uint64_t idx = 1; idx < sd.N; ++idx) {
    Eigen::Vector3d f = imu_f.row(idx).transpose();
    Eigen::Vector3d w = imu_w.row(idx).transpose();
    preintegrated->integrateMeasurement(f, w, dt);

    bool is_update_step = (idx + 1) % 10 == 0;

    if (is_update_step) {
      correction_count++;
      double timestamp = idx * dt;

      graph.resize(0);
      values.clear();
      timestamps.clear();

      // Add IMU factor
      if constexpr (UseSE23) {
        Factor imu_factor(X(correction_count - 1), X(correction_count),
                          B(correction_count - 1), B(correction_count),
                          *preintegrated);
        graph.add(imu_factor);
      } else {
        Factor imu_factor(X(correction_count - 1), V(correction_count - 1),
                          X(correction_count), V(correction_count),
                          B(correction_count - 1), B(correction_count),
                          *preintegrated);
        graph.add(imu_factor);
      }

      // Predict + insert initial values
      if constexpr (UseSE23) {
        gtsam::ExtendedPose3 prop_state =
            preintegrated->predict(prev_state, prev_bias_estimate);
        values.insert(X(correction_count), prop_state);
        values.insert(B(correction_count), prev_bias_estimate);
        timestamps[X(correction_count)] = timestamp;
        timestamps[B(correction_count)] = timestamp;
      } else {
        gtsam::NavState prop_state =
            preintegrated->predict(prev_state, prev_bias_estimate);
        values.insert(X(correction_count), prop_state.pose());
        values.insert(V(correction_count), prop_state.v());
        values.insert(B(correction_count), prev_bias_estimate);
        timestamps[X(correction_count)] = timestamp;
        timestamps[V(correction_count)] = timestamp;
        timestamps[B(correction_count)] = timestamp;
      }

      // Determine active aiding: when using PARS, bootstrap with GNSS first
      bool in_bootstrap = (timestamp < gnss_bootstrap_duration);
      Aiding active_aiding =
          (opts.aiding_scheme == Aiding::PARSFull && in_bootstrap)
              ? Aiding::GNSS
              : opts.aiding_scheme;

      // Add aiding factors
      if (active_aiding == Aiding::GNSS) {
        gtsam::Point3 gps_meas(gnss_pos(0, idx), gnss_pos(1, idx),
                               gnss_pos(2, idx));
        if constexpr (UseSE23) {
          graph.add(GPSFactorSE23(X(correction_count), gps_meas, gnss_noise));
        } else {
          graph.add(gtsam::GPSFactor(X(correction_count), gps_meas, gnss_noise));
        }
      } else if (active_aiding == Aiding::PARSFull) {
        using PoseParam =
            std::conditional_t<UseSE23, gtsam::ExtendedPose3, gtsam::Pose3>;
        for (const auto& beacon : beacons) {
          double range = beacon.z(0, idx);
          double elevation = beacon.z(1, idx);
          double azimuth = beacon.z(2, idx);

          graph.add(parnav::RangeFactor<PoseParam>(
              X(correction_count), range_noise, range, beacon.origin));
          graph.add(parnav::AzimuthFactor<PoseParam>(
              X(correction_count), azimuth_noise, azimuth, beacon.origin));
          graph.add(parnav::ElevationFactor<PoseParam>(
              X(correction_count), elevation_noise, elevation, beacon.origin));
        }
      }

      // Update smoother
      smoother.update(graph, values, timestamps);

      // Extract results
      gtsam::Values result = smoother.calculateEstimate();
      gtsam::Rot3 R_est;
      gtsam::Point3 p_est;
      gtsam::Vector3 v_est;
      if constexpr (UseSE23) {
        auto ext = result.at<gtsam::ExtendedPose3>(X(correction_count));
        prev_state = ext;
        R_est = ext.rotation();
        p_est = ext.position();
        v_est = ext.velocity();
      } else {
        prev_state =
            gtsam::NavState(result.at<gtsam::Pose3>(X(correction_count)),
                            result.at<gtsam::Vector3>(V(correction_count)));
        R_est = prev_state.pose().rotation();
        p_est = prev_state.pose().translation();
        v_est = prev_state.v();
      }
      prev_bias_estimate = result.at<BIAS>(B(correction_count));

      preintegrated->resetIntegrationAndSetBias(prev_bias_estimate);

      // Store estimates
      est_pos.push_back(p_est);
      est_vel.push_back(v_est);
      est_att.push_back(R_est);
      est_acc_bias.push_back(prev_bias_estimate.accelerometer());
      est_gyro_bias.push_back(prev_bias_estimate.gyroscope());

      // Compute errors
      Eigen::Vector3d p_err =
          p_est -
          Eigen::Vector3d(true_pos(0, idx), true_pos(1, idx), true_pos(2, idx));
      Eigen::Vector3d v_err =
          v_est -
          Eigen::Vector3d(true_vel(0, idx), true_vel(1, idx), true_vel(2, idx));

      // Attitude error (Euler angles): R_err = R_true^T * R_est
      gtsam::Rot3 R_true =
          gtsam::Rot3::Quaternion(true_att(0, idx), true_att(1, idx),
                                  true_att(2, idx), true_att(3, idx));
      Eigen::Vector3d a_err(ssa(R_est.roll() - R_true.roll()),
                            ssa(R_est.pitch() - R_true.pitch()),
                            ssa(R_est.yaw() - R_true.yaw()));

      // Bias errors
      Eigen::Vector3d ab_err =
          prev_bias_estimate.accelerometer() -
          Eigen::Vector3d(true_ab(0, idx), true_ab(1, idx), true_ab(2, idx));
      Eigen::Vector3d gb_err =
          prev_bias_estimate.gyroscope() -
          Eigen::Vector3d(true_gb(0, idx), true_gb(1, idx), true_gb(2, idx));

      pos_err.push_back(p_err);
      vel_err.push_back(v_err);
      att_err.push_back(a_err);
      acc_bias_err.push_back(ab_err);
      gyro_bias_err.push_back(gb_err);

      // Extract 3-sigma bounds from marginal covariances.
      // Legacy: Pose3 cov 6x6 [rot(3), pos(3)], Vel 3x3, Bias 6x6 [acc, gyro].
      // SE23:   ExtendedPose3 cov 9x9 [theta(3), nu(3), rho(3)], Bias 6x6.
      Eigen::Matrix<double, 15, 1> sig3;
      try {
        if constexpr (UseSE23) {
          gtsam::Matrix ext_cov =
              smoother.marginalCovariance(X(correction_count));
          gtsam::Matrix bias_cov =
              smoother.marginalCovariance(B(correction_count));
          // roll, pitch, yaw
          sig3(0) = 3.0 * std::sqrt(ext_cov(0, 0));
          sig3(1) = 3.0 * std::sqrt(ext_cov(1, 1));
          sig3(2) = 3.0 * std::sqrt(ext_cov(2, 2));
          // vel (nu block, 3-5)
          sig3(6) = 3.0 * std::sqrt(ext_cov(3, 3));
          sig3(7) = 3.0 * std::sqrt(ext_cov(4, 4));
          sig3(8) = 3.0 * std::sqrt(ext_cov(5, 5));
          // pos (rho block, 6-8)
          sig3(3) = 3.0 * std::sqrt(ext_cov(6, 6));
          sig3(4) = 3.0 * std::sqrt(ext_cov(7, 7));
          sig3(5) = 3.0 * std::sqrt(ext_cov(8, 8));
          sig3(9) = 3.0 * std::sqrt(bias_cov(0, 0));
          sig3(10) = 3.0 * std::sqrt(bias_cov(1, 1));
          sig3(11) = 3.0 * std::sqrt(bias_cov(2, 2));
          sig3(12) = 3.0 * std::sqrt(bias_cov(3, 3));
          sig3(13) = 3.0 * std::sqrt(bias_cov(4, 4));
          sig3(14) = 3.0 * std::sqrt(bias_cov(5, 5));
        } else {
          gtsam::Matrix pose_cov =
              smoother.marginalCovariance(X(correction_count));
          gtsam::Matrix vel_cov =
              smoother.marginalCovariance(V(correction_count));
          gtsam::Matrix bias_cov =
              smoother.marginalCovariance(B(correction_count));
          sig3(0) = 3.0 * std::sqrt(pose_cov(0, 0));
          sig3(1) = 3.0 * std::sqrt(pose_cov(1, 1));
          sig3(2) = 3.0 * std::sqrt(pose_cov(2, 2));
          sig3(3) = 3.0 * std::sqrt(pose_cov(3, 3));
          sig3(4) = 3.0 * std::sqrt(pose_cov(4, 4));
          sig3(5) = 3.0 * std::sqrt(pose_cov(5, 5));
          sig3(6) = 3.0 * std::sqrt(vel_cov(0, 0));
          sig3(7) = 3.0 * std::sqrt(vel_cov(1, 1));
          sig3(8) = 3.0 * std::sqrt(vel_cov(2, 2));
          sig3(9) = 3.0 * std::sqrt(bias_cov(0, 0));
          sig3(10) = 3.0 * std::sqrt(bias_cov(1, 1));
          sig3(11) = 3.0 * std::sqrt(bias_cov(2, 2));
          sig3(12) = 3.0 * std::sqrt(bias_cov(3, 3));
          sig3(13) = 3.0 * std::sqrt(bias_cov(4, 4));
          sig3(14) = 3.0 * std::sqrt(bias_cov(5, 5));
        }
      } catch (const std::exception& e) {
        sig3.setZero();
      }
      three_sigma.push_back(sig3);

      if (correction_count % 100 == 0) {
        printf("Step %llu/%llu | Pos: %.4f m | Vel: %.4f m/s | Att: %.4f deg\n",
               static_cast<unsigned long long>(idx),
               static_cast<unsigned long long>(sd.N), p_err.norm(),
               v_err.norm(), rad2deg(a_err.norm()));
      }
    }
  }

  auto end_time = std::chrono::system_clock::now();
  std::chrono::duration<double> elapsed = end_time - start_time;
  printf("Elapsed time: %.3f s | Data horizon: %.1f s\n", elapsed.count(),
         sd.N * dt);

  // --- Export results to CSV ---
  std::string bias_tag =
      std::is_same_v<BIAS, gtsam::imuBias::GaussMarkovBias> ? "gm" : "cb";
  std::string se23_tag = UseSE23 ? "_se23" : "";
  std::string output_file =
      opts.output_dir + "gtsam_fork_test_" + bias_tag + se23_tag + ".csv";
  std::ofstream out(output_file);
  if (!out) {
    std::cerr << "Error: Could not open output file " << output_file << "\n";
    return;
  }

  out << "pos_n,pos_e,pos_d,vel_n,vel_e,vel_d,roll,pitch,yaw,"
      << "pos_err_n,pos_err_e,pos_err_d,vel_err_n,vel_err_e,vel_err_d,"
      << "att_err_roll,att_err_pitch,att_err_yaw,"
      << "acc_bias_err_x,acc_bias_err_y,acc_bias_err_z,"
      << "gyro_bias_err_x,gyro_bias_err_y,gyro_bias_err_z,"
      << "sig3_roll,sig3_pitch,sig3_yaw,"
      << "sig3_pos_n,sig3_pos_e,sig3_pos_d,"
      << "sig3_vel_n,sig3_vel_e,sig3_vel_d,"
      << "sig3_ab_x,sig3_ab_y,sig3_ab_z,"
      << "sig3_gb_x,sig3_gb_y,sig3_gb_z\n";

  size_t n_results = std::min(est_pos.size(), pos_err.size());
  for (size_t i = 0; i < n_results; ++i) {
    const auto& ep = est_pos[i + 1];  // skip initial
    const auto& ev = est_vel[i + 1];
    const auto& ea = est_att[i + 1];
    const auto& pe = pos_err[i];
    const auto& ve = vel_err[i];
    const auto& ae = att_err[i];
    const auto& abe = acc_bias_err[i];
    const auto& gbe = gyro_bias_err[i];
    const auto& s3 = three_sigma[i];
    char buf[2048];
    snprintf(buf, sizeof(buf),
             "%.6f,%.6f,%.6f,%.6f,%.6f,%.6f,%.6f,%.6f,%.6f,"
             "%.6f,%.6f,%.6f,%.6f,%.6f,%.6f,"
             "%.6f,%.6f,%.6f,"
             "%.6f,%.6f,%.6f,"
             "%.6f,%.6f,%.6f,"
             "%.8f,%.8f,%.8f,"
             "%.8f,%.8f,%.8f,"
             "%.8f,%.8f,%.8f,"
             "%.8f,%.8f,%.8f,"
             "%.8f,%.8f,%.8f\n",
             ep.x(), ep.y(), ep.z(), ev.x(), ev.y(), ev.z(), ea.roll(),
             ea.pitch(), ea.yaw(), pe.x(), pe.y(), pe.z(), ve.x(), ve.y(),
             ve.z(), ae.x(), ae.y(), ae.z(), abe.x(), abe.y(), abe.z(), gbe.x(),
             gbe.y(), gbe.z(), s3(0), s3(1), s3(2), s3(3), s3(4), s3(5), s3(6),
             s3(7), s3(8), s3(9), s3(10), s3(11), s3(12), s3(13), s3(14));
    out << buf;
  }

  printf("Saved results to %s\n", output_file.c_str());

  printf("Preintegration: %s\n", UseSE23 ? "ManifoldSE23" : "Manifold");
}

// ============================================================================
// Main
// ============================================================================

namespace {

void print_usage(const char* prog) {
  std::cerr
      << "Usage: " << prog << " [options]\n"
      << "  --bias {gm|cb}           bias model (default: gm)\n"
      << "                           gm = 1st-order Gauss-Markov,\n"
      << "                           cb = constant / random-walk bias\n"
      << "  --preint {se23|legacy}   preintegrator (default: se23)\n"
      << "                           se23   = ManifoldPreintegrationSE23 +\n"
      << "                                    CombinedImuFactor2 on ExtendedPose3\n"
      << "                           legacy = ManifoldPreintegration +\n"
      << "                                    CombinedImuFactor on (Pose3, Vector3)\n"
      << "  --aiding {gnss|pars}     aiding scheme (default: pars)\n"
      << "  --input <path>           input simulation CSV\n"
      << "  --output-dir <path>      output directory for result CSVs\n"
      << "  -h, --help               show this help and exit\n";
}

bool parse_args(int argc, char** argv, Options& opts) {
  auto need_value = [&](int i, const std::string& flag) {
    if (i + 1 >= argc) {
      std::cerr << "Error: " << flag << " requires a value\n";
      return false;
    }
    return true;
  };
  for (int i = 1; i < argc; ++i) {
    std::string a = argv[i];
    if (a == "-h" || a == "--help") {
      print_usage(argv[0]);
      std::exit(0);
    } else if (a == "--bias") {
      if (!need_value(i, a)) return false;
      std::string v = argv[++i];
      if (v == "gm") opts.use_gauss_markov = true;
      else if (v == "cb") opts.use_gauss_markov = false;
      else { std::cerr << "Unknown --bias value: " << v << "\n"; return false; }
    } else if (a == "--preint") {
      if (!need_value(i, a)) return false;
      std::string v = argv[++i];
      if (v == "se23") opts.use_se23 = true;
      else if (v == "legacy") opts.use_se23 = false;
      else { std::cerr << "Unknown --preint value: " << v << "\n"; return false; }
    } else if (a == "--aiding") {
      if (!need_value(i, a)) return false;
      std::string v = argv[++i];
      if (v == "gnss") opts.aiding_scheme = Aiding::GNSS;
      else if (v == "pars") opts.aiding_scheme = Aiding::PARSFull;
      else { std::cerr << "Unknown --aiding value: " << v << "\n"; return false; }
    } else if (a == "--input") {
      if (!need_value(i, a)) return false;
      opts.input_file = argv[++i];
    } else if (a == "--output-dir") {
      if (!need_value(i, a)) return false;
      opts.output_dir = argv[++i];
      if (!opts.output_dir.empty() && opts.output_dir.back() != '/')
        opts.output_dir.push_back('/');
    } else {
      std::cerr << "Unknown argument: " << a << "\n";
      print_usage(argv[0]);
      return false;
    }
  }
  return true;
}

}  // namespace

int main(int argc, char* argv[]) {
  Options opts;
  if (!parse_args(argc, argv, opts)) return 1;

  printf("Reading simulation data from: %s\n", opts.input_file.c_str());
  auto sd = read_simulation_csv(opts.input_file);
  if (!sd) {
    return 1;
  }
  printf("Loaded %llu time steps at %d Hz\n",
         static_cast<unsigned long long>(sd->N), sd->freq());
  printf("Number of PARS beacons: %d\n", sd->num_locators());
  printf("Mode: %s\n", opts.use_se23 ? "SE_2(3) CombinedImuFactor2"
                                     : "Legacy CombinedImuFactor");
  printf("Aiding: %s\n",
         opts.aiding_scheme == Aiding::PARSFull ? "PARS (GNSS bootstrap)"
                                                : "GNSS");

  // Runtime dispatch to the 4 (BIAS, UseSE23) template instantiations.
  using GM = gtsam::imuBias::GaussMarkovBias;
  using CB = gtsam::imuBias::ConstantBias;

  try {
    if (opts.use_gauss_markov) {
      printf(
          "Using 1st-order Gauss-Markov bias model (tau_acc=%.0f s, "
          "tau_gyro=%.0f s)\n",
          tau_acc, tau_gyro);
      if (opts.use_se23)
        run_estimation<GM, true>(*sd, opts);
      else
        run_estimation<GM, false>(*sd, opts);
    } else {
      printf("Using constant (random walk) bias model\n");
      if (opts.use_se23)
        run_estimation<CB, true>(*sd, opts);
      else
        run_estimation<CB, false>(*sd, opts);
    }
  } catch (const gtsam::IndeterminantLinearSystemException& e) {
    std::cerr << "IndeterminantLinearSystemException: " << e.what() << "\n";
  } catch (const std::exception& e) {
    std::cerr << "Exception: " << e.what() << "\n";
  }

  return 0;
}
